module RailsCredentialsCipher
  VERSION: String

  class Error < StandardError
  end

  def self.decrypt: (?environment: String?, ?out: IO) -> Pathname
  def self.encrypt: (?environment: String?, ?out: IO) -> Pathname
  def self.cipher: (?environment: String?) -> Cipher

  class Cipher
    attr_reader encrypted_path: Pathname
    attr_reader key_path: Pathname
    attr_reader env_key: String
    attr_reader plain_path: Pathname

    def initialize: (encrypted_path: String | Pathname, key_path: String | Pathname, ?env_key: String, ?plain_path: (String | Pathname)?) -> void
    def decrypt: () -> Pathname
    def encrypt: () -> Pathname?
  end
end
